services:
  postgres:
    image: 'postgres:latest'
    container_name: 'url_shortener_postgresql'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "${DB_PORT}:5432"
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'url_shortener_rebbitmq'
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
    ports:
      - '5672:5672'
      - '15672:15672'
  redis:
    image: 'redis:latest'
    container_name: 'url_shortener_redis'
    ports:
      - '6379'
